### ISSUE TITLE
第五节变换里的代码有问题呀。

### ISSUE THREAD

**Issue by zihuyishi** [AttackOnDobby/iOS-Core-Animation-Advanced-Techniques#23]
https://github.com/AttackOnDobby/iOS-Core-Animation-Advanced-Techniques/blob/master/5-%E5%8F%98%E6%8D%A2/%E5%8F%98%E6%8D%A2.md#%E5%85%89%E4%BA%AE%E5%92%8C%E9%98%B4%E5%BD%B1

- (void)applyLightingToFace:(CALayer *)face
{
 .....
    CATransform3D transform = face.transform;
    GLKMatrix4 matrix4 = *(GLKMatrix4 *)&transform;  
这里GLKMatrix4和CATransform3D内存布局不一样呀。

我自己测试时用的是如下代码转换的
- (GLKMatrix4)matrixFrom3DTransformation:(CATransform3D)transform
{
    GLKMatrix4 matrix = GLKMatrix4Make(transform.m11, transform.m12, transform.m13, transform.m14,
                                       transform.m21, transform.m22, transform.m23, transform.m24,
                                       transform.m31, transform.m32, transform.m33, transform.m34,
                                       transform.m41, transform.m42, transform.m43, transform.m44);
    
    return matrix;
}

**Comment by AttackOnDobby** [comment]
内存布局确实是一样的呀，本质都是存放16个float类型的结构体，不同的是GLKMatrix4用了一个m数组来存放值组成union，不过一般这种做法多数用来在寄存器位定义，方便标记位的存取，所以作者代码是能够build通过的~

**Comment by zihuyishi** [comment]
我ios 8.1的sdk里CATransform3D是CGFloat,不是float类型

**Comment by AttackOnDobby** [comment]
嗯理论上在64位机器上会有精度损失，已修复，thx：）

**Comment by edisongz** [comment]
第五章的内容有重复，比如你可以搜索“扁平化图层”，有重复内容。

**Comment by lyj98** [comment]
- (GLKMatrix4)matrixFrom3DTransformation:(CATransform3D)transform
{
    GLKMatrix4 matrix = GLKMatrix4Make(transform.m11, transform.m12, transform.m13, transform.m14,
                                       transform.m21, transform.m22, transform.m23, transform.m24,
                                       transform.m31, transform.m32, transform.m33, transform.m34,
                                       transform.m41, transform.m42, transform.m43, transform.m44);

    return matrix;
}

增加这个方法,转换一下
