### ISSUE TITLE
配图和代码 不搭配 

### ISSUE THREAD

**Issue by qxw** [AttackOnDobby/iOS-Core-Animation-Advanced-Techniques#24]
隐式动画  97行
用来在每次颜色变化结束之后切换到另一个旋转90的动画。代码见清单7.3，运行结果见图7.2。

代码和说明都是90度  但是配图可能是45度的

**Comment by AttackOnDobby** [comment]
刚check了一下原书的配图和代码确实不匹配，所以猜测作者配图的意图应该是想表明动画执行的过程XD
