### ISSUE TITLE
能否做成gitbook呢?

### ISSUE THREAD

**Issue by xiwang126** [AttackOnDobby/iOS-Core-Animation-Advanced-Techniques#25]
感谢你开源出这么好的东西, 辛苦了! 能否把你的翻译的书做成gitbook放在自己博客站里, 不提供下载,只有网页版gitbook,  就像这样
http://numbbbbb.gitbooks.io/-the-swift-programming-language-/content/index.html

**Comment by xiwang126** [comment]
里面的内容, 包括作者信息都会保留的

**Comment by AttackOnDobby** [comment]
awesome！不过现在时间有限，等有空闲会做的~
