### ISSUE TITLE
翻译不准确

### ISSUE THREAD

**Issue by NathanLi** [AttackOnDobby/iOS-Core-Animation-Advanced-Techniques#26]
--------------------------------------
第3章图层几何学
锚点处：
之前提到过，视图的center属性和图层的position属性都指定了相对于父图层anchorPoint的位置
--------------------------------------

会让人误以为这里的anchorPoint指的是父图层的anchorPoint。
再原文意思应该是：
之前提到过，视图的center属性和图层的position属性都指定了图层anchorPoint相对于父图层的位置

**Comment by AttackOnDobby** [comment]
已merge，thx：）
