### ISSUE TITLE
你好，不知道你对把本书放上gitbook有什么想法？

### ISSUE THREAD

**Issue by ZsIsMe** [AttackOnDobby/iOS-Core-Animation-Advanced-Techniques#45]
我觉得本书内容和你翻译的资料都是极好的，但在github上的阅读体验不是太好...
不知你对将本书放上gitbook有什么看法呢？
https://www.gitbook.com/explore
如果你愿意的话，我希望可以尽绵薄之力将其重新排版放上去（我也能借此学习下markdown），译者写你的名字，不会做其他用途。
你认为呢？
感谢你的劳动！

**Comment by AttackOnDobby** [comment]
之前有小伙伴提过，最近一直忙着别的杂事儿，要是大家愿意帮忙排版的话当然好啦，译者写大家的名字就好啦~

**Comment by ZsIsMe** [comment]
你好，我已经开动了，但是有些问题想问问，我可不可以在你翻译的基础上，进行一些排版上的修改？本人比较懒，希望在3月份前弄好，还有请问可不可给我你的联系方式？QQ.邮件都可以。

**Comment by AttackOnDobby** [comment]
邮件fxu1990@gmail.com

**Comment by AttackOnDobby** [comment]
邮件fxu1990@gmail.com
